package com.example.quizapp

data class Question(
    val id: Int,
    val question: String,
    val image: Int,
    val optionOne: String,
    val optionTwo: String,
    val optionThree: String,
    val optionFour: String,
    val correctAnswer: Int
)

data class Country(val name: String, val code: String, val imageloc: Int)

var allcountries = ArrayList<Country>() // This is an empty list

fun initialize(){
    allcountries.add(Country("Andorra", "ad",R.drawable.ad))
    allcountries.add(Country("United Arab Emirates", "ae",R.drawable.ae))
    allcountries.add(Country("Afghanistan", "af",R.drawable.af))
    allcountries.add(Country("Antigua and Barbuda", "ag",R.drawable.ag))
    allcountries.add(Country("Anguilla", "ai",R.drawable.ai))
    allcountries.add(Country("Albania", "al",R.drawable.al))
    allcountries.add(Country("Armenia", "am",R.drawable.am))
    allcountries.add(Country("Angola", "ao",R.drawable.ao))
    allcountries.add(Country("Antarctica", "aq",R.drawable.aq))
    allcountries.add(Country("Argentina", "ar",R.drawable.ar))
    allcountries.add(Country("American Samoa", "as",R.drawable.as_))
    allcountries.add(Country("Austria", "at",R.drawable.at))
    allcountries.add(Country("Australia", "au",R.drawable.au))
    allcountries.add(Country("Aruba", "aw",R.drawable.aw))
    allcountries.add(Country("Aland Islands", "ax",R.drawable.ax))
    allcountries.add(Country("Azerbaijan", "az",R.drawable.az))
    allcountries.add(Country("Bosnia and Herzegovina", "ba",R.drawable.ba))
    allcountries.add(Country("Barbados", "bb",R.drawable.bb))
    allcountries.add(Country("Bangladesh", "bd",R.drawable.bd))
    allcountries.add(Country("Belgium", "be",R.drawable.be))
    allcountries.add(Country("Burkina Faso", "bf",R.drawable.bf))
    allcountries.add(Country("Bulgaria", "bg",R.drawable.bg))
    allcountries.add(Country("Bahrain", "bh",R.drawable.bh))
    allcountries.add(Country("Burundi", "bi",R.drawable.bi))
    allcountries.add(Country("Benin", "bj",R.drawable.bj))
    allcountries.add(Country("Saint Barthelemy", "bl",R.drawable.bl))
    allcountries.add(Country("Bermuda", "bm",R.drawable.bm))
    allcountries.add(Country("Brunei Darussalam", "bn",R.drawable.bn))
    allcountries.add(Country("Bolivia", "bo",R.drawable.bo))
    allcountries.add(Country("Caribbean Netherlands", "bq",R.drawable.bq))
    allcountries.add(Country("Brazil", "br",R.drawable.br))
    allcountries.add(Country("Bahamas", "bs",R.drawable.bs))
    allcountries.add(Country("Bhutan", "bt",R.drawable.bt))
    allcountries.add(Country("Bouvet Island", "bv",R.drawable.bv))
    allcountries.add(Country("Botswana", "bw",R.drawable.bw))
    allcountries.add(Country("Belarus", "by",R.drawable.by))
    allcountries.add(Country("Belize", "bz",R.drawable.bz))
    allcountries.add(Country("Canada", "ca",R.drawable.ca))
    allcountries.add(Country("Cocos Islands", "cc",R.drawable.cc))
    allcountries.add(Country("Congo", "cd",R.drawable.cd))
    allcountries.add(Country("Central African Republic", "cf",R.drawable.cf))
    allcountries.add(Country("Congo", "cg",R.drawable.cg))
    allcountries.add(Country("Switzerland", "ch",R.drawable.ch))
    allcountries.add(Country("Cote D'ivoire", "ci",R.drawable.ci))
    allcountries.add(Country("Cook Islands", "ck",R.drawable.ck))
    allcountries.add(Country("Chile", "cl",R.drawable.cl))
    allcountries.add(Country("Cameroon", "cm",R.drawable.cm))
    allcountries.add(Country("China", "cn",R.drawable.cn))
    allcountries.add(Country("Colombia", "co",R.drawable.co))
    allcountries.add(Country("Costa Rica", "cr",R.drawable.cr))
    allcountries.add(Country("Cuba", "cu",R.drawable.cu))
    allcountries.add(Country("Cape Verde", "cv",R.drawable.cv))
    allcountries.add(Country("Curacao", "cw",R.drawable.cw))
    allcountries.add(Country("Christmas Island", "cx",R.drawable.cx))
    allcountries.add(Country("Cyprus", "cy",R.drawable.cy))
    allcountries.add(Country("Czech Republic", "cz",R.drawable.cz))
    allcountries.add(Country("Germany", "de",R.drawable.de))
    allcountries.add(Country("Djibouti", "dj",R.drawable.dj))
    allcountries.add(Country("Denmark", "dk",R.drawable.dk))
    allcountries.add(Country("Dominica", "dm",R.drawable.dm))
    allcountries.add(Country("Dominican Republic", "dr",R.drawable.dr))
    allcountries.add(Country("Algeria", "dz",R.drawable.dz))
    allcountries.add(Country("Ecuador", "ec",R.drawable.ec))
    allcountries.add(Country("Estonia", "ee",R.drawable.ee))
    allcountries.add(Country("Egypt", "eg",R.drawable.eg))
    allcountries.add(Country("Western Sahara", "eh",R.drawable.eh))
    allcountries.add(Country("Eritrea", "er",R.drawable.er))
    allcountries.add(Country("Spain", "es",R.drawable.es))
    allcountries.add(Country("Ethiopia", "et",R.drawable.et))
    allcountries.add(Country("Finland", "fi",R.drawable.fi))
    allcountries.add(Country("Fiji", "fj",R.drawable.fj))
    allcountries.add(Country("Falkland Islands", "fk",R.drawable.fk))
    allcountries.add(Country("Macaronesia", "fm",R.drawable.fm))
    allcountries.add(Country("Faroe Islands", "fo",R.drawable.fo))
    allcountries.add(Country("France", "fr",R.drawable.fr))
    allcountries.add(Country("Gabon", "ga",R.drawable.ga))
    allcountries.add(Country("Great Britain", "gb",R.drawable.gb))
    allcountries.add(Country("England", "gb_eng",R.drawable.gb_eng))
    allcountries.add(Country("Northern Ireland", "gb_nir",R.drawable.gb_nir))
    allcountries.add(Country("Scotland", "gb_sct",R.drawable.gb_sct))
    allcountries.add(Country("Wales", "gb_wls",R.drawable.gb_wls))
    allcountries.add(Country("Grenada", "gd",R.drawable.gd))
    allcountries.add(Country("Georgia", "ge",R.drawable.ge))
    allcountries.add(Country("French Guiana", "gf",R.drawable.gf))
    allcountries.add(Country("Guernsey", "gg",R.drawable.gg))
    allcountries.add(Country("Ghana", "gh",R.drawable.gh))
    allcountries.add(Country("Gibraltar", "gi",R.drawable.gi))
    allcountries.add(Country("Greenland", "gl",R.drawable.gl))
    allcountries.add(Country("Gambia", "gm",R.drawable.gm))
    allcountries.add(Country("Guinea", "gn",R.drawable.gn))
    allcountries.add(Country("Guadeloupe", "gp",R.drawable.gp))
    allcountries.add(Country("Equatorial Guinea", "gq",R.drawable.gq))
    allcountries.add(Country("Greece", "gr",R.drawable.gr))
    allcountries.add(Country("South Georgia and the South Sandwich Islands", "gs",R.drawable.gs))
    allcountries.add(Country("Guatemala", "gt",R.drawable.gt))
    allcountries.add(Country("Guam", "gu",R.drawable.gu))
    allcountries.add(Country("Guinea-Bissau", "gw",R.drawable.gw))
    allcountries.add(Country("Guyana", "gy",R.drawable.gy))
    allcountries.add(Country("Hong Kong", "hk",R.drawable.hk))
    allcountries.add(Country("Heard Island and McDonald Island", "hm",R.drawable.hm))
    allcountries.add(Country("Honduras", "hn",R.drawable.hn))
    allcountries.add(Country("Croatia", "hr",R.drawable.hr))
    allcountries.add(Country("Haiti", "ht",R.drawable.ht))
    allcountries.add(Country("Hungary", "hu",R.drawable.hu))
    allcountries.add(Country("Indonesia", "id",R.drawable.id))
    allcountries.add(Country("Ireland", "ie",R.drawable.ie))
    allcountries.add(Country("Israel", "il",R.drawable.il))
    allcountries.add(Country("Isle of Man", "im",R.drawable.im))
    allcountries.add(Country("India", "in",R.drawable.in_))
    allcountries.add(Country("British Indian Ocean Territory", "io",R.drawable.io))
    allcountries.add(Country("Iraq", "iq",R.drawable.iq))
    allcountries.add(Country("Iran", "ir",R.drawable.ir))
    allcountries.add(Country("Iceland", "is",R.drawable.is_))
    allcountries.add(Country("Italy", "it",R.drawable.it))
    allcountries.add(Country("Jamaica", "jm",R.drawable.jm))
    allcountries.add(Country("Jordan", "jo",R.drawable.jo))
    allcountries.add(Country("Japan", "jp",R.drawable.jp))
    allcountries.add(Country("Kenya", "ke",R.drawable.ke))
    allcountries.add(Country("Kyrgyzstan", "kg",R.drawable.kg))
    allcountries.add(Country("Cambodia", "kh",R.drawable.kh))
    allcountries.add(Country("Kiribati", "ki",R.drawable.ki))
    allcountries.add(Country("Comoros", "km",R.drawable.km))
    allcountries.add(Country("Saint Kitts and Nevis", "kn",R.drawable.kn))
    allcountries.add(Country("North Korea", "kp",R.drawable.kp))
    allcountries.add(Country("South Koreas", "kr",R.drawable.kr))
    allcountries.add(Country("Kuwait", "kw",R.drawable.kw))
    allcountries.add(Country("Cayman Islands", "ky",R.drawable.ky))
    allcountries.add(Country("Kazakhstan", "kz",R.drawable.kz))
    allcountries.add(Country("Lao", "la",R.drawable.la))
    allcountries.add(Country("Lebanon", "lb",R.drawable.lb))
    allcountries.add(Country("Saint Lucia", "lc",R.drawable.lc))
    allcountries.add(Country("Liechtenstein", "li",R.drawable.li))
    allcountries.add(Country("Sri Lanka", "lk",R.drawable.lk))
    allcountries.add(Country("Libera", "lr",R.drawable.lr))
    allcountries.add(Country("Lesotho", "ls",R.drawable.ls))
    allcountries.add(Country("ithuania", "lt",R.drawable.lt))
    allcountries.add(Country("Luxembourg", "lu",R.drawable.lu))
    allcountries.add(Country("Latvia", "lv",R.drawable.lv))
    allcountries.add(Country("Libyan Arab Jamahiriya", "ly",R.drawable.ly))
    allcountries.add(Country("Morocco", "ma",R.drawable.ma))
    allcountries.add(Country("Monaco", "mc",R.drawable.mc))
    allcountries.add(Country("Moldova", "md",R.drawable.md))
    allcountries.add(Country("Montenegro", "me",R.drawable.me))
    allcountries.add(Country("Madagascar", "mg",R.drawable.mg))
    allcountries.add(Country("Marshall Islands", "mh",R.drawable.mh))
    allcountries.add(Country("Macedonia", "mk",R.drawable.mk))
    allcountries.add(Country("Mali", "ml",R.drawable.ml))
    allcountries.add(Country("Myanmar", "mm",R.drawable.mm))
    allcountries.add(Country("Mongolia", "mn",R.drawable.mn))
    allcountries.add(Country("Macao", "mo",R.drawable.mo))
    allcountries.add(Country("Northern Mariana Islands", "mp",R.drawable.mp))
    allcountries.add(Country("Martinique", "mq",R.drawable.mq))
    allcountries.add(Country("Mauritania", "mr",R.drawable.mr))
    allcountries.add(Country("Monserrat", "ms",R.drawable.ms))
    allcountries.add(Country("Malta", "mt",R.drawable.mt))
    allcountries.add(Country("Mauritius", "mu",R.drawable.mu))
    allcountries.add(Country("Maldives", "mv",R.drawable.mv))
    allcountries.add(Country("Malawi", "mw",R.drawable.mw))
    allcountries.add(Country("Mexico", "mx",R.drawable.mx))
    allcountries.add(Country("Malaysia", "my",R.drawable.my))
    allcountries.add(Country("Mozambique", "mz",R.drawable.mz))
    allcountries.add(Country("Namibia", "na",R.drawable.na))
    allcountries.add(Country("New Caledonia", "nc",R.drawable.nc))
    allcountries.add(Country("Niger", "ne",R.drawable.ne))
    allcountries.add(Country("Norfolk Island", "nf",R.drawable.nf))
    allcountries.add(Country("Nigeria", "ng",R.drawable.ng))
    allcountries.add(Country("Nicaragua", "ni",R.drawable.ni))
    allcountries.add(Country("Netherlands", "nl",R.drawable.nl))
    allcountries.add(Country("Norway", "no",R.drawable.no))
    allcountries.add(Country("Nepal", "np",R.drawable.np))
    allcountries.add(Country("Nauru", "nr",R.drawable.nr))
    allcountries.add(Country("Niue", "nu",R.drawable.nu))
    allcountries.add(Country("New Zealand", "nz",R.drawable.nz))
    allcountries.add(Country("Oman", "om",R.drawable.om))
    allcountries.add(Country("Panama", "pa",R.drawable.pa))
    allcountries.add(Country("Peru", "pe",R.drawable.pe))
    allcountries.add(Country("French Polynesia", "pf",R.drawable.pf))
    allcountries.add(Country("Papua New Guinea", "pg",R.drawable.pg))
    allcountries.add(Country("Philippines", "ph",R.drawable.ph))
    allcountries.add(Country("Pakistan", "pk",R.drawable.pk))
    allcountries.add(Country("Poland", "pl",R.drawable.pl))
    allcountries.add(Country("Saint Pierre and Miquelon", "pm",R.drawable.pm))
    allcountries.add(Country("Pitcairn", "pn",R.drawable.pn))
    allcountries.add(Country("Puerto Rico", "pr",R.drawable.pr))
    allcountries.add(Country("Palestine", "ps",R.drawable.ps))
    allcountries.add(Country("Portugal", "pt",R.drawable.pt))
    allcountries.add(Country("Palau", "pw",R.drawable.pw))
    allcountries.add(Country("Paraguay", "py",R.drawable.py))
    allcountries.add(Country("Qatar", "qa",R.drawable.qa))
    allcountries.add(Country("Reunion", "re",R.drawable.re))
    allcountries.add(Country("Romania", "ro",R.drawable.ro))
    allcountries.add(Country("Serbia","rs",R.drawable.rs))
    allcountries.add(Country("Russia", "ru",R.drawable.ru))
    allcountries.add(Country("Rwanda", "rw",R.drawable.rw))
    allcountries.add(Country("Saudi Arabia", "sa",R.drawable.sa))
    allcountries.add(Country("Solomon Islands", "sb",R.drawable.sb))
    allcountries.add(Country("Seychelles", "sc",R.drawable.sc))
    allcountries.add(Country("Sudan", "sd",R.drawable.sd))
    allcountries.add(Country("Sweden", "se",R.drawable.se))
    allcountries.add(Country("Singapore", "sg",R.drawable.sg))
    allcountries.add(Country("Saint Helena", "sh",R.drawable.sh))
    allcountries.add(Country("Slovenia", "si",R.drawable.si))
    allcountries.add(Country("Svalbard and Jan Mayen", "sj",R.drawable.sj))
    allcountries.add(Country("Slovakia", "sk",R.drawable.sk))
    allcountries.add(Country("Sierra Leone", "sl",R.drawable.sl))
    allcountries.add(Country("San Marino", "sm",R.drawable.sm))
    allcountries.add(Country("Senegal", "sn",R.drawable.sn))
    allcountries.add(Country("Somalia", "so",R.drawable.so))
    allcountries.add(Country("Suriname", "sr",R.drawable.sr))
    allcountries.add(Country("South Sudan", "ss",R.drawable.ss))
    allcountries.add(Country("Sao Tome and Principe", "st",R.drawable.st))
    allcountries.add(Country("El Salvador", "sv",R.drawable.sv))
    allcountries.add(Country("Saint Maarten", "sx",R.drawable.sx))
    allcountries.add(Country("Syria Arab Republic", "sy",R.drawable.sy))
    allcountries.add(Country("Swaziland", "sz",R.drawable.sz))
    allcountries.add(Country("Turks and Caicos Islands", "tc",R.drawable.tc))
    allcountries.add(Country("Chad", "td",R.drawable.td))
    allcountries.add(Country("French Southern Territories", "tf",R.drawable.tf))
    allcountries.add(Country("Togo", "tg",R.drawable.tg))
    allcountries.add(Country("Thailand", "th",R.drawable.th))
    allcountries.add(Country("Tajikistan", "tj",R.drawable.tj))
    allcountries.add(Country("Tokelau", "tk",R.drawable.tk))
    allcountries.add(Country("Timor_Leste", "tl",R.drawable.tl))
    allcountries.add(Country("Turkmenistan", "tm",R.drawable.tm))
    allcountries.add(Country("Tunisia", "tn",R.drawable.tn))
    allcountries.add(Country("Tonga", "to",R.drawable.to))
    allcountries.add(Country("Turkey", "tr",R.drawable.tr))
    allcountries.add(Country("Trinidad and Tobago", "tt",R.drawable.tt))
    allcountries.add(Country("Tuvalu", "tv",R.drawable.tv))
    allcountries.add(Country("Taiwan", "tw",R.drawable.tw))
    allcountries.add(Country("Tanzania", "tz",R.drawable.tz))
    allcountries.add(Country("Ukraine", "ua",R.drawable.ua))
    allcountries.add(Country("Uganda", "ug",R.drawable.ug))
    allcountries.add(Country("United States", "us",R.drawable.us))
    allcountries.add(Country("Uruguay", "uy",R.drawable.uy))
    allcountries.add(Country("Uzbekistan", "uz",R.drawable.uz))
    allcountries.add(Country("Vatican", "va",R.drawable.va))
    allcountries.add(Country("Saint Vincent and the Grenadines", "vc",R.drawable.vc))
    allcountries.add(Country("Venezuela", "ve",R.drawable.ve))
    allcountries.add(Country("British Virgin Islands", "vg",R.drawable.vg))
    allcountries.add(Country("U.S. Virgin Islands", "vi",R.drawable.vi))
    allcountries.add(Country("Vietnam", "vn",R.drawable.vn))
    allcountries.add(Country("Wallis and Futana", "vu",R.drawable.vu))
    allcountries.add(Country("Samoa", "wf",R.drawable.wf))
    allcountries.add(Country("Kosovo", "ws",R.drawable.ws))
    allcountries.add(Country("Yemen", "xk",R.drawable.xk))
    allcountries.add(Country("Mayotte", "ye",R.drawable.ye))
    allcountries.add(Country("South Africa", "yt",R.drawable.yt))
    allcountries.add(Country("Zambia", "za",R.drawable.za))
    allcountries.add(Country("Zimbabwe", "zm",R.drawable.zm))
}
